---
all:
  children:
    routers:
      hosts:
        R1:
          ansible_host: 192.168.74.141
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_command_timeout: 180
          #ansible_shell_type: sh
          ansible_shell_executable: /bin/bash
        R2:
          ansible_host: 192.168.74.141
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_command_timeout: 180
          #ansible_shell_type: sh
          ansible_shell_executable: /bin/bash
        R3:
          ansible_host: 192.168.74.141
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_command_timeout: 180
          #ansible_shell_type: sh
          ansible_shell_executable: /bin/bash
      vars:
      
        ansible_ssh_user: bcuit
        ansible_ssh_pass: security  
        #ansible_ssh_port: 22